name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: mac-os

    steps:
    - uses: actions/checkout@v3
    - name: make clean
      working-directory: ./ref
      run: make clean
    - name: make
      working-directory: ./ref
      run: make
    - name: run exe
      working-directory: ./ref
      run: ./wave
